### PR TITLE
Modernise type hints

### PR DESCRIPTION
**Pull request by KapJI**
[python-typing-update](https://github.com/cdce8p/python-typing-update) is created by HA maintainers to update type hints to the new [PEP 585](https://www.python.org/dev/peps/pep-0585/) style.

Old ones will be deprecated in Python 3.9 and eventually removed few year later. Before that they can be used with:
```python
from __future__ import annotations
```

The advantage is that they don't need to be imported and python authors don't need to maintain parallel type definitions in `typing` module. Basically this is the future of python.

This tool can be run with:
```shell
poetry run pre-commit run --hook-stage manual python-typing-update --all-files
```

It can only run on committed files, because of that we can't add it to default `pre-commit` workflow. Otherwise you want be able to commit files if it modified something. But can add it to linting job.

### CODE REVIEW

**Comment by DurgNomis-drol** [comment]
A couple of questions:
1. Will this require us to run `poetry run pre-commit run --hook-stage manual python-typing-update --all-files` before every commit?
2. Is this just another syntax for using typing?

**Comment by KapJI** [comment]
1. You don't have to as long you don't forget to use these modern syntax. Otherwise CI will catch it.
2. Yes, it's added by [PEP 585](https://www.python.org/dev/peps/pep-0585/).

**Comment by DurgNomis-drol** [comment]
Right, thanks clarifying. 

It seems cleaner to use the new type hints then 😃

**Comment by KapJI** [comment]
The only limitation of this new syntax is that it can only be used for type hints but can't be used in the code itself (e.g. for `isinstance`, `cast` or type aliases like `JsonDict`) before Python 3.9 is the default. HA is planning to switch to 3.9 in the end of this year.

**Comment by DurgNomis-drol** [comment]
Right, so we will stil need to use the old syntax in the code? 

If above is the case, then I think it will become confusing for people if we use two different syntax's for typing.

**Comment by KapJI** [comment]
In very limited cases. I think right now `JsonDict` is the only place where it's needed. This is the style I'm trying to adopt from HA Core codebase.

**Comment by DurgNomis-drol** [comment]
HA core does not use type annotations in the code itself. There by not having the same problem as us. 

What does @leikoilja think?

**Comment by KapJI** [comment]
> HA core does not use type annotations in the code itself.
That's not true. Open any file here for example.
https://github.com/home-assistant/core/tree/dev/homeassistant/helpers

**Comment by DurgNomis-drol** [comment]
I think I misunderstood what you meant with `can't be used in the code itself`.

**Comment by KapJI** [comment]
I mean code which is executed by python interpreter.

For example type hints are not executed, only `mypy` uses them.
But on the other hand `isinstance(List[str], my_list)` is code which is executed by interpreter.

**Comment by DurgNomis-drol** [comment]
Thanks for clarifying, I understand it now. 😄 

This sounds great!

**Review by leikoilja — APPROVED** [review]
This is very nice! 
Typing can be a bit confusing at time, and i'm also just grasping my idea around it, so as long as we have someone like @KapJI who can take a solid lead on it - I'm all hands for it! 🚀

**Pull request merged**
