### PR TITLE
Translate services to all supported languages

### PR DESCRIPTION
**Pull request by KapJI**
Translate services description.

Translated using GPT4, so it may not be exactly accurate but should be good enough, at least for languages I can verify.

Feel free to submit corrections if you notice any.

### CODE REVIEW

**Comment by KapJI** [comment]
cc @pschneider87, @leoledmag, @heehoo59, @jumping2000, @petrepa, @emile-bodin, @GaworskiRafal, @LeandroIssa, @mdiazgoncalves, @misa1515, @denysdovhan as you initially added one of these translations.

**Review by leikoilja — APPROVED** [review]
haha, not much i can review here, but thanks a lot for adding new translation for all the services 🔥

**Comment by leikoilja** [comment]
@DurgNomis-drol  @ArnyminerZ, you guys spoke Danish and Spanish if i m not mistaken, care to review as well? :)

**Comment by KapJI** [comment]
Can update translations in the next PR if any comments arise.

**Review by ArnyminerZ — COMMENTED** [review]
Spanish and Catalan translations look good

**Review by mdiazgoncalves — COMMENTED** [review]
Portuguese looks good to me.

**Pull request merged**
