### PR TITLE
Replace 'off' state with 'unavailable'

### LINKED ISSUE #114: Invalid timestamp
## Describe the bug

I was getting "Unavailable" on v.1 on alarms and timers but now get "Invalid Timestamp" on v1.1.0 

## Version of the integration

```text
V1.1.0
```

## Glocaltokens Version (Underlying package)

```text
Add pip information here.
```

## Logs

```

2021-03-25 20:15:37 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-03-25 20:15:43 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform meross_cloud is taking over 10 seconds.
2021-03-25 20:16:37 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: google_home
2021-03-25 20:16:47 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-03-25 20:16:47 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-03-25 20:16:47 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-03-25 20:16:47 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-03-25 20:16:47 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-03-25 20:16:47 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-03-25 20:16:47 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
```

## Debug log

```yaml
logger:
  default: debug
  logs:
    custom_components.google_home: debug
```

```text

Add your debug logs here.

```

### PR DESCRIPTION
**Pull request by KapJI**
Fully match [next alarm sensor](https://companion.home-assistant.io/docs/core/sensors/#next-alarm-sensor) state format.

Fixes #114.

### CODE REVIEW

**Review by leikoilja — APPROVED** [review]
Beautiful 💯 
Thank you 💥

**Comment by craigmcgowan** [comment]
Thank you

**Comment by leikoilja** [comment]
@KapJI let's just use one of the labels here, cause both of those are used for `release-drafter`. patch only bumps up `x.x.Y` while minor `x.Y.x`. This is probs `patch` IMHO

**Comment by KapJI** [comment]
I think I misclicked it 🙂

**Comment by r0667002** [comment]
I would have preferred the 'off' state tbh. I was using this integration (thank you btw, it's awesome) to trigger a morning automation. If the sensor went from "<<some_timestamp>>" to "off", that meant I stopped the alarm and I'd get out of bed. 

The problem is, sometimes my speaker/the integration goes unavailable throughout the day or in the middle of the night.
That means: if this happens while an alarm is set, my morning automation will trigger and wake up everyone in the house (news starts playing on all of the speakers). The difference between "off" and "unavailable" is thus quite big for me.

Sad thing is that this integration has now become useless to me :(

**Comment by DurgNomis-drol** [comment]
Why can't you just check if it is `unavailable` instead of `off`? 🤔

**Comment by KapJI** [comment]
I think if device is really unavailable, the state should be `unknown`. If it's not, it's a bug.

**Comment by r0667002** [comment]
> Why can't you just check if it is `unavailable` instead of `off`? 🤔

Because then if my speaker/integration goes unavailable because it's actually unavailable instead of me turning off the alarm, the automation could trigger randomly 😄

**Comment by r0667002** [comment]
> I think if device is really unavailable, the state should be `unknown`. If it's not, it's a bug.
> 
> Unfortunately, with device class `timestamp`, we can't use `off`.

Alright, I'll check! Thanks 😄

**Comment by DurgNomis-drol** [comment]
@r0667002 Right, that makes sense 😄 Hope you find a solution

**Pull request merged**
