### PR TITLE
Added Norwegian 🇳🇴

### PR DESCRIPTION
**Pull request by petrepa**
Added both written languages of Norwegian:

- **nn:** Nynorsk
- **nb:** Bokmål

Was unsure whether or not to also commit a change to the README to add the two new languages, as this was not stated in the language contributing guide lines, so I haven't done it as of now 😅 Understandable if the OG maintainer of this repo would have the full control of the README.

### CODE REVIEW

**Review by ArnyminerZ — APPROVED** [review]
Awesome! Looks great to me. Let's keep adding languages 🚀

**Comment by ArnyminerZ** [comment]
Yes, as you have said, please @petrepa, add your change to the README, please.

**Comment by petrepa** [comment]
Added a new commit with a suggestion to the documentation 😄

**Review by ArnyminerZ — APPROVED** [review]

**Comment by ArnyminerZ** [comment]
Well, this shouldn't happen, @KapJI should have more idea on how to get around this.

**Review by leikoilja — APPROVED** [review]
This is amazing! Thanks for adding both the translations and the guidelines to the README! 💥 🚀

**Comment by leikoilja** [comment]
I can see that codespells are failing on `json` file, but this is a false positive imho. Let's merge in the translations, since they are unrelated to codespell and I have just added a separate PR #263 to ignore `json` files further on

**Pull request merged**
