### PR TITLE
Add installs badge

### PR DESCRIPTION
**Pull request by KapJI**
I found data about custom integration installs at https://analytics.home-assistant.io/custom_integrations.json

Created small endpoint on RunKit to create badge data for [shields.io](https://shields.io/endpoint):
https://runkit.com/kapji/google-home-installs-for-shield-io

### CODE REVIEW

**Review by leikoilja — APPROVED** [review]
This is increadible! For a long time, I was curious if people use the integration and if they are then how many are they. This is sooo inspiring and humbling to see that so many people use the integration. So so so amazing! 💥 

Thank you tons @KapJI, @DurgNomis-drol, @ArnyminerZ, @Drakulix 💥 🔥 💯

**Comment by DurgNomis-drol** [comment]
I second @leikoilja comment!

**Comment by DurgNomis-drol** [comment]
@KapJI I hope it is okay, but you inspired me to add these badges to another integration i'm making. So thanks!!!

I actually learned a lot through this project, thanks especially to you @leikoilja and @KapJI.

**Comment by KapJI** [comment]
Sure, free free to use it! Glad you're finding this helpful 🙂

**Comment by leikoilja** [comment]
@KapJI, thanks tons for implementing this one, super interesting stats 💥  
As our community grows, I was wondering if it would be cool to either expand the existing badge or add another similar one with the integration's popularity? 
I think for that we can use the same `json` to extract `total install` from all other packages and compare the numeric popularity of `Ha-Google-Home` integration? What do you think?

**Comment by leikoilja** [comment]
Well that shows popularity of installs amount all HA users. We can either display that or what i was thinking grabbing data from `https://analytics.home-assistant.io/custom_integrations.json` and comparing relative amount of installs between all custom HACS integrations. So it will end up being like: `we have 2000 install` and this is `10/321`, 10th of 321 3rd party integrations our there.

**Pull request merged**
