### PR TITLE
Add config option for changing update interval.

### PR DESCRIPTION
**Pull request by DurgNomis-drol**
As discussed in #202 and [comment](https://github.com/leikoilja/ha-google-home/issues/202#issuecomment-895221500)

Adds ability for the user to change the update interval. This will make it possible for users who suffer for timeout problems to change their update interval as it seems this can help with it.

Also this now sets the default update interval to 180 seconds instead of 10 as pointed out in comment. Users should at their own risk tune it what they need.

This does not close. #202 but gives users more options to try to mitigate it.

### CODE REVIEW

**Review by leikoilja — APPROVED** [review]
Looks good, thanks for fixing it!

Were you able to validate it's working locally? :) 
It would be so so nice to add a few lines to "README" about integration limitations explaining that the fetch rate is 3min and the user can tune it at their own risk. If we add it in the first part of README it can save a lot of time to some people. What do you think? (Edit: just saw your other comment that you were thinking of making a README as a separate PR. Sounds great 🚀 )

**Comment by DurgNomis-drol** [comment]
Thanks for approving🎉 I tested it locally and it works for me. 😊

**Review by KapJI — APPROVED** [review]
Looks good, thanks!

**Comment by leikoilja** [comment]
@DurgNomis-drol before we can release it in a next public release, can you please draft your thoughts regarding limitations in `README`? :)

**Comment by DurgNomis-drol** [comment]
Yes, I will try to get it done later today 😊

**Pull request merged**
