### PR TITLE
Parse labels to timers and alarms

### PR DESCRIPTION
**Pull request by DurgNomis-drol**
Parses the `label` attribute to make it possible to show the name/label of the timer/alarm when it has one.

### CODE REVIEW

**Review by leikoilja — APPROVED** [review]
Wait what, you can set a label for a timer/alarm? :smile:  How do you do that?

**Comment by DurgNomis-drol** [comment]
😆 

You can say `with the name 'Pizza' afterwards.` But there are many ways you can fraise the that so it picks it up. I also suspect it is very different for each language how many ways there is 😄

**Comment by leikoilja** [comment]
haha, that's nice, i didn't know! Thanks for adding it, that would be so useful! :smile:  Was cooking yesterday and using two timers was confusing cause i didn't know which is which :smile:

**Comment by DurgNomis-drol** [comment]
I know the feeling 😄

**Pull request merged**
