### PR TITLE
Fix no-member warning

### PR DESCRIPTION
**Pull request by KapJI**
This file is pretty messy.
- `state` is defined on `sensor` level
- It was using `_name` from child classes
- `entry` is not used
- rename `_name` to `device_name`. Varible name starting with `_` usually means that it's not used, that's not true here
I tested that it still works after these changes.

### CODE REVIEW

**Comment by leikoilja** [comment]
Uuu,, that's amazing, thanks @KapJI. Let's keep this PR open before we can knock out #77, since there are a lot of changes affecting these files. Once the #77 is merged, i ll get back to this one to rebase and apply those changes too :)

**Comment by leikoilja** [comment]
haha, @KapJI did we just both force pushed rebase changes fixing this branch? 😄

**Review by leikoilja — APPROVED** [review]
Looks good to me, thanks for cleaning it up! 💥

**Comment by KapJI** [comment]
> haha, @KapJI did we just both force pushed rebase changes fixing this branch? 😄

yeah, looks like it 😀

**Comment by leikoilja** [comment]
Anyways, I'm happy with it! Thanks 💥

**Pull request merged**
