### PR TITLE
First batch of pylint fixes

### PR DESCRIPTION
**Pull request by KapJI**
Fix some problems and enable pylint checks to prevent them in future.

Also fix `pre-commit` config for poetry.

### CODE REVIEW

**Review by leikoilja — APPROVED** [review]
Looks great to me! Thanks for picking it up! Let's merge it when you feel it's ready! 💥

**Comment by KapJI** [comment]
It's ready :) New fixed will come in new PRs.

**Comment by leikoilja** [comment]
@KapJI, try using label where possible - they are very helpful for automatic release drafts

**Comment by KapJI** [comment]
Documentation feels not relevant here.

**Pull request merged**
