### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by KapJI**
Version bump.

### CODE REVIEW

**Review by DurgNomis-drol — APPROVED** [review]
LGTM 😄 This will hopefully solve a lot of bugs!

**Comment by leikoilja** [comment]
Let's do it 🤩💥

**Comment by DurgNomis-drol** [comment]
I just tested it on Home Assistant 2021.4 and everything seems to work. 😄

**Comment by leikoilja** [comment]
Thank you, @DurgNomis-drol for testing and @KapJI for the release 💥

**Pull request merged**
