### PR TITLE
catch all exceptions in api.py Fetching data loop.

### PR DESCRIPTION
**Pull request by vlebourl**
raise when it's a dangerous exception.

### CODE REVIEW

**Comment by KapJI** [comment]
What exception did you get which is not yet catched?

**Comment by vlebourl** [comment]
sorry... going to fast with my commits...
I get this:
```
/!\ ERROR: <class 'asyncio.exceptions.TimeoutError'>
```
which I know, is printed by HA like this:
```
2021-04-09 17:40:20 ERROR (MainThread) [custom_components.google_home] Timeout fetching sensor data
```
later on, but I thought that way we can know where the timeout precisely comes from.
If you judge that unnecessary, please do not hesitate to discard that PR. I'll keep that change private ;-)

**Comment by vlebourl** [comment]
Also, one of my device is constantly in a timeout, maybe allowing to set the timeout as an option in the config flow could be helpful. but I guess that would be another PR!

**Comment by DurgNomis-drol** [comment]
@vlebourl First of all you have to use pre-commit and make sure that everything passes if you want your PR to be reviewed. 😄 See  [Contributions.md](https://github.com/leikoilja/ha-google-home/blob/master/CONTRIBUTING.mdl.

Second, this just print there error. We still need a way to handle it. But first we need to understand why it is happening with some device and not others.

**Comment by KapJI** [comment]
We shouldn't actually catch generic `Exception`. Instead we need to list exceptions which we're expecting to get. Everything else should go to the top level and be reported as a bug.

**Pull request closed without merging**
