### PR TITLE
Add docs for fetching token using container

### PR DESCRIPTION
**Pull request by KapJI**
I messed up with https://github.com/leikoilja/ha-google-home/pull/772

Credits to @Brephlas

### CODE REVIEW

**Review by leikoilja — APPROVED** [review]
Thanks @KapJI for fixing it & @Brephlas for contribution!

**Review by leikoilja — APPROVED** [review]

**Comment by owenvoke** [comment]
I had a couple of questions about this Docker image. Is the `Dockerfile` available anywhere? 👀

And also, if this is solely for this purpose, would it make more sense for the `CMD` to run the `get_tokens.py` script, rather than `bash` so you don't have to connect to the image and leave it running in the background in a detached state?

That way it would just be a case of running this, rather than 3 commands.
```shell
docker run --rm -it breph/ha-google-home_get-token:latest
```

**Comment by Brephlas** [comment]
It is now :) https://github.com/Brephlas/dockerfile_breph-ha-google-home_get-token/tree/master

Regarding the second question: I like the idea and played a little bit with this. Unfortunately, it seems it is not possible to run interactive scripts using this method. At least when asking for user input, the script fails. 
So I think we have two options:
1) stick to the current flow
2) change it, but require to pass username and password using `-e` docker environment variables. But I am not sure if I like that one because the credentials are then inside of the history

**Comment by owenvoke** [comment]
Hi @Brephlas, I've just tested it locally (changing `CMD bash` to `CMD python3 get_tokens.py`) and [it seems to work perfectly](https://asciinema.org/a/T3lXiV9usVuDLQrILvOrel009) with `docker run --rm -it [image]`. 🤔 I'm using macOS, and iTerm2.

<details>
<summary>Preview video</summary>

[asciicast](https://asciinema.org/a/T3lXiV9usVuDLQrILvOrel009)

</details>

Also related to this image, I wonder if we could change to using Alpine to reduce the image size. 🤷🏻
```dockerfile
FROM alpine:3.18

WORKDIR /app

RUN apk add py3-pip
COPY ./get_tokens.py .
COPY ./requirements.txt .
RUN python3 -m pip install -r ./requirements.txt

CMD python3 get_tokens.py
```

This reduces the image from `606MB` to `96.7MB` 🙂

I guess `device_id`, `master_token`, and `access_token` would probably all make sense as having configurable by Docker secrets.

**Comment by Brephlas** [comment]
Thanks @owenvoke. Apparently, the issue was sitting in front of the screen, I missed the `-it` parameter 😅 
It now worked in my local tests and I've already updated the image to alpine and pushed it to dockerhub.  
Will update the docs of this repo in a sec

Regarding the docker secrets we can move the discussion to my repo. However, until now I have no experience with docker secrets

**Pull request merged**
