### PR TITLE
Add workaround for GLIBC issue in troubleshooting

### LINKED ISSUE #543: GLIBC_2.34 not available  Home Assistant version 2022.6.0
## Describe the bug

Error occurred loading configuration flow for integration google_home: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by /home/john/homeassistant/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so)

## Version of the integration
 v1.9.11 , v1.912
If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Add version here.
```

## Logs

```text
Add your logs here.
```

### PR DESCRIPTION
**Pull request by KapJI**
Closes #543

### CODE REVIEW

**Comment by DurgNomis-drol** [comment]
Does this work on all architectures?

**Review by leikoilja — APPROVED** [review]
Nice! Thanks for adding it to README 💪

**Comment by KapJI** [comment]
@DurgNomis-drol yes, it should.

**Comment by TheMcBain92** [comment]
Tried it on my rpi last night and just got a bunch of errors. Will try again so I can copy the error I get.

**Comment by TheMcBain92** [comment]
> Tried it on my rpi last night and just got a bunch of errors. Will try again so I can copy the error I get.

This is the Error I gen when I run the new command.

`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting grpcio==1.46.1
  Using cached grpcio-1.46.1.tar.gz (21.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mswb2roy/grpcio_4d3dcbb131a3429396444f11e29aaa8d/setup.py", line 257, in <module>
          if check_linker_need_libatomic():
        File "/tmp/pip-install-mswb2roy/grpcio_4d3dcbb131a3429396444f11e29aaa8d/setup.py", line 204, in check_linker_need_libatomic
          cpp_test = subprocess.Popen(cxx + ['-x', 'c++', '-std=c++11', '-'],
        File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'c++'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by KapJI** [comment]
You need to install the compiler. `sudo apt install -y build-essential` if you're on debian based system.

**Comment by TheMcBain92** [comment]
> You need to install the compiler. `sudo apt install -y build-essential` if you're on debian based system.

Wouldn't let me install this because of dependency issues :( more digging required.

**Pull request merged**
