### PR TITLE
Update release-drafter.yml

### PR DESCRIPTION
**Pull request by KapJI**
Move bug fixes to the top. They are usually more important.

### CODE REVIEW

**Review by leikoilja — APPROVED** [review]
Good point, haven't even though about setting an order here

**Comment by KapJI** [comment]
Also moved `performance` to features 🙂

**Comment by leikoilja** [comment]
is performance a feature? 🤔  quite philosophical question i guess

**Comment by KapJI** [comment]
I'd say it's closer to feature than to anything else.
Something like `it's 2x faster` worth putting in the features list 🙂

**Pull request merged**
